#! /bin/bash

pdub_dir=$HOME/.pdub
pdubs_file=$pdub_dir/pdubs.json

if ! which gpg >/dev/null; then
  echo "ERROR: no 'gpg' found"
  exit 1
fi

if [ ! -d $pdub_dir ]; then
  mkdir $pdub_dir
  chmod 700 $pdub_dir
fi

echo -n "Password: "
stty -echo
read password
stty echo
echo ''

if [ ! -f "${pdubs_file}.gpg" ]; then
  touch "$pdubs_file"
  gpg --symmetric --yes --passphrase "$password" -o "$pdubs_file"
  rm "$pdubs_file"
fi

if [ "`stat -f '%p' ${pdubs_file}.gpg`" -gt 100600 ]; then
  chmod 600 ${pdubs_file}.gpg
fi

pdub_vim="$(dirname $0)/pdub.vim"

my_vim="vim"
if which mvim &>/dev/null; then
  my_vim="mvim"
fi

gpg -d --passphrase $password ${pdubs_file}.gpg | \
  $my_vim -n -c "let password = \"$password\"" \
             -c "let filename = \"${pdubs_file}.gpg\"" \
             -c "set filetype=json" \
             -c "source $pdub_vim" -

chmod 600 ${pdubs_file}.gpg
