"set lines=50
"set columns=100
set guioptions=egmrLt 
if exists('&transparency')
	set transparency=2
endif
autocmd BufRead *.safari setfiletype html
noremap <D-[> gT
noremap <D-]> gt
colorscheme solarized
set guioptions-=m
