set guioptions=egrt 
if exists('&transparency')
	set transparency=2
endif
autocmd BufRead *.safari setfiletype html
noremap <D-[> gT
noremap <D-]> gt
colorscheme solarized
set guifont=Consolas:h12
" set guifont=Inconsolata:h11
nmap <SwipeDown> <c-w>j<c-w>_
nmap <SwipeUp> <c-w>k<c-w>_
