set guioptions=egrt 
if exists('&transparency')
	set transparency=2
endif
autocmd BufRead *.safari setfiletype html
noremap <D-[> gT
noremap <D-]> gt

" colorscheme solarized
colorscheme railscasts
hi ColorColumn guibg=#242424
hi NonText guifg=#242424
hi StatusLine guifg=#E6E1DC guibg=#211714
hi StatusLineNC guifg=#211714 guibg=#E6E1DC


set guifont=Consolas:h12
" set guifont=Inconsolata:h11

map <SwipeUp> <C-W>j:silent call<space>MaximizeWithoutResizingQuickfix()<cr>
map <SwipeDown> <C-W>k:silent call<space>MaximizeWithoutResizingQuickfix()<cr>
nmap <SwipeLeft> gT
nmap <SwipeRight> gt

highlight NonText    guifg=#181210
highlight SpecialKey guifg=#181210

let g:CommandTAcceptSelectionSplitMap='<C-CR>'
let g:CommandTAcceptSelectionTabMap='<CR>'
